import type { PublicCategory, PublicDriver, PublicStage } from "./public-data";

export const fallbackDrivers: PublicDriver[] = [
  {
    id: "fallback-walison",
    slug: "walison-goncalves",
    name: "Walison Gonçalves",
    fullName: "Walison Gonçalves",
    number: 7,
    category: "Ultras Insanos",
    categorySlug: "insanos",
    categoryColor: "#00D9FF",
    points: 112,
    grossPoints: 112,
    discardedPoints: 0,
    wins: 3,
    podiums: 5,
    poles: 0,
    position: 1,
    previousPosition: null,
    avatarUrl: null,
    heroImageUrl: null,
    teamName: null,
    city: "Betim/MG",
    bio: null,
  },
  {
    id: "fallback-haroldo",
    slug: "haroldo-alves",
    name: "Haroldo Alves",
    fullName: "Haroldo Alves",
    number: 79,
    category: "Ultras Insanos",
    categorySlug: "insanos",
    categoryColor: "#00D9FF",
    points: 104,
    grossPoints: 104,
    discardedPoints: 0,
    wins: 2,
    podiums: 5,
    poles: 0,
    position: 2,
    previousPosition: null,
    avatarUrl: null,
    heroImageUrl: null,
    teamName: null,
    city: "Betim/MG",
    bio: null,
  },
  {
    id: "fallback-aldo",
    slug: "aldo-senna",
    name: "Aldo Senna",
    fullName: "Aldo Senna",
    number: 44,
    category: "Ultras Rápidos",
    categorySlug: "rapidos",
    categoryColor: "#F7F5F0",
    points: 98,
    grossPoints: 98,
    discardedPoints: 0,
    wins: 2,
    podiums: 4,
    poles: 0,
    position: 1,
    previousPosition: null,
    avatarUrl: null,
    heroImageUrl: null,
    teamName: null,
    city: "Betim/MG",
    bio: null,
  },
  {
    id: "fallback-pedro",
    slug: "pedro-guilherme",
    name: "Pedro Guilherme",
    fullName: "Pedro Guilherme Lemos Teixeira",
    number: 70,
    category: "Ultras Rápidos",
    categorySlug: "rapidos",
    categoryColor: "#F7F5F0",
    points: 91,
    grossPoints: 91,
    discardedPoints: 0,
    wins: 1,
    podiums: 4,
    poles: 0,
    position: 2,
    previousPosition: null,
    avatarUrl: null,
    heroImageUrl: null,
    teamName: null,
    city: "Betim/MG",
    bio: null,
  },
  {
    id: "fallback-arthur",
    slug: "arthur-henrique",
    name: "Arthur Henrique",
    fullName: "Arthur Henrique Vieira da Silva",
    number: 56,
    category: "Ultras Rápidos",
    categorySlug: "rapidos",
    categoryColor: "#F7F5F0",
    points: 84,
    grossPoints: 84,
    discardedPoints: 0,
    wins: 0,
    podiums: 3,
    poles: 0,
    position: 3,
    previousPosition: null,
    avatarUrl: null,
    heroImageUrl: null,
    teamName: null,
    city: "Betim/MG",
    bio: null,
  },
];

export const fallbackStages: PublicStage[] = [
  {
    id: "fallback-stage-1",
    slug: "endurance-agosto",
    date: "18 AGO",
    title: "Resistência",
    format: "endurance",
    track: "Traçado 01 invertido com chicane",
    time: "21h",
    startsAt: "2026-08-18T21:00:00-03:00",
    status: "registration",
    location: "Kartódromo Internacional de Betim",
    city: "Betim/MG",
    registrationOpensAt: null,
    registrationClosesAt: null,
    trackMapUrl: null,
    heroImageUrl: null,
    shortDescription: null,
  },
  {
    id: "fallback-stage-2",
    slug: "etapa-setembro",
    date: "08 SET",
    title: "Etapa regular",
    format: "regular",
    track: "Traçado 02 normal e invertido",
    time: "21h",
    startsAt: "2026-09-08T21:00:00-03:00",
    status: "registration",
    location: "Kartódromo Internacional de Betim",
    city: "Betim/MG",
    registrationOpensAt: null,
    registrationClosesAt: null,
    trackMapUrl: null,
    heroImageUrl: null,
    shortDescription: null,
  },
  {
    id: "fallback-stage-3",
    slug: "etapa-outubro",
    date: "13 OUT",
    title: "Etapa regular",
    format: "regular",
    track: "Traçado 05 normal e invertido",
    time: "21h",
    startsAt: "2026-10-13T21:00:00-03:00",
    status: "registration",
    location: "Kartódromo Internacional de Betim",
    city: "Betim/MG",
    registrationOpensAt: null,
    registrationClosesAt: null,
    trackMapUrl: null,
    heroImageUrl: null,
    shortDescription: null,
  },
  {
    id: "fallback-stage-4",
    slug: "etapa-novembro",
    date: "10 NOV",
    title: "Etapa regular",
    format: "regular",
    track: "Traçado 11 normal e invertido",
    time: "21h",
    startsAt: "2026-11-10T21:00:00-03:00",
    status: "registration",
    location: "Kartódromo Internacional de Betim",
    city: "Betim/MG",
    registrationOpensAt: null,
    registrationClosesAt: null,
    trackMapUrl: null,
    heroImageUrl: null,
    shortDescription: null,
  },
  {
    id: "fallback-stage-5",
    slug: "final-endurance",
    date: "12 DEZ",
    title: "Final de resistência",
    format: "endurance",
    track: "Traçado 01 normal",
    time: "11h",
    startsAt: "2026-12-12T11:00:00-03:00",
    status: "registration",
    location: "Kartódromo Internacional de Betim",
    city: "Betim/MG",
    registrationOpensAt: null,
    registrationClosesAt: null,
    trackMapUrl: null,
    heroImageUrl: null,
    shortDescription: null,
  },
];

export const fallbackCategories: PublicCategory[] = [
  { slug: "insanos", name: "Ultras Insanos", color: "#00D9FF" },
  { slug: "rapidos", name: "Ultras Rápidos", color: "#F7F5F0" },
];
